from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.Dashboard, name='dashboard'),
    path('profile/', views.Profile, name='profile'),
    path('edit_account/', views.EditAccount, name='edit_account'),
    path('upload_player_profile/', views.UploadPlayerProfile, name='upload_player_profile'),
    path('update_player_profile/', views.UpdatePlayerProfile, name='update_player_profile'),
    path('upload_coach_profile/', views.uploadcoachprofile, name='upload_coach_profile'),
    path('update_coach_profile/', views.updatecoachprofile, name='update_coach_profile'),
    path('change_password/', views.ChangePassword, name='change_password'),
    path('my_statistics/', views.MyStatistics, name='my_statistics'),
    path('upload_match_statistics/', views.UploadMatchStatistics, name='upload_match_statistics'),
    path('upload_player_ratings/', views.UploadPlayerRatings, name='upload_player_ratings'),
    path('update_player_ratings/', views.updateplayerratings, name='update_player_ratings'),
    path('player_database/', views.playerdatabase, name='player_database'),
    # path('player_search/', views.playersearch, name='player_search'),
    path('players_cart/', views.playerscart, name='players_cart'),
    path('manage_players/', views.playermanagement, name='manage_players'),
    path('add_player/<id>/', views.addplayer, name='add_player'),
    path('player_profile/<id>/', views.playerprofile, name='player_profile'),
    path('upload&update_player_profile_agent/<id>/', views.uploadandupdateplayerprofile, name='upload&update_player_profile_agent'),
    path('change_player_password/<id>/', views.changeplayerpassword, name='change_player_password'),
    path('player_statistics_view/<id>/', views.playerstatisticsview, name='player_statistics_view'),
    path('edit_player_account/<id>/', views.editplayeraccount, name='edit_player_account'),
    path('match_results/<id>/', views.MatchResults, name='match_results'),
    path('manage_player_ratings/<id>/', views.manageplayerratings, name='manage_player_ratings'),
    path('upload_player_match_record/<id>/', views.uploadplayermatchrecord, name='upload_player_match_record'),
    path('update_player_match_record/<id>/<mid>/', views.updateplayermatchrecord, name='update_player_match_record'),
    path('delete_player_match_record/<id>/<mid>/', views.deleteplayermatchrecord, name='delete_player_match_record'),
    path('player_video_upload/<id>/', views.playervideouploadview, name='player_video_upload'),
    path('manage_player_videos/<id>/', views.manageplayervideos, name='manage_player_videos'),
    path('player_video_view/<id>/<vid>/', views.playervideoview, name='player_video_view'),
    path('delete_player_video/<id>/<vid>/', views.deleteplayervideo, name='delete_player_video'),
    path('player_video_list/<id>/', views.playervideolistview, name='player_video_list'),
    path('upload_video/', views.myvideouploadview, name='upload_video'),
    path('my_video_gallery/', views.myvideos, name='my_video_gallery'),
    path('update_match_statistics/<id>/', views.UpdateMatchStatistics, name='update_match_statistics'),
    path('delete_match_record/<id>/', views.DeleteMatchRecord, name='delete_match_record'),
    path('individual_player_statistics/<id>/', views.PlayerStatistics, name='individual_player_statistics'),
    path('individual_match_record/<id>/<mid>/', views.IndividualMatchResult, name='individual_match_result'),
    path('videos/<category>/', views.categoryvideos, name="videos")
]