# Generated by Django 3.0.7 on 2020-11-20 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True)),
                ('category', models.CharField(max_length=20)),
                ('video', models.FileField(default=None, upload_to='videos/')),
                ('date_of_publish', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamina', models.DecimalField(decimal_places=2, max_digits=4)),
                ('durability', models.DecimalField(decimal_places=2, max_digits=4)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pass_accuracy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('shot_accuracy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='user-profile.png', upload_to='uploads/player_profile')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('strong_foot', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=40, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True)),
                ('team', models.CharField(blank=True, max_length=30, null=True)),
                ('team_icon', models.ImageField(default=None, upload_to='uploads/team_icon')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=10)),
                ('venue', models.CharField(blank=True, max_length=30)),
                ('played_for', models.CharField(blank=True, max_length=30)),
                ('played_against', models.CharField(blank=True, max_length=30)),
                ('team_score', models.IntegerField(blank=True)),
                ('opponent_score', models.IntegerField(blank=True)),
                ('goals_scored', models.IntegerField(blank=True)),
                ('assist', models.IntegerField(blank=True)),
                ('yellow_card', models.CharField(blank=True, max_length=5)),
                ('red_card', models.CharField(blank=True, max_length=5)),
                ('league', models.CharField(blank=True, max_length=30, null=True)),
                ('team_icon', models.ImageField(default=None, upload_to='uploads/team_icon')),
                ('opponent_icon', models.ImageField(default=None, upload_to='uploads/opponent_icon')),
                ('shots_on_target', models.IntegerField(blank=True, null=True)),
                ('passes_completed', models.IntegerField(blank=True, null=True)),
                ('distance_covered', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saves', models.IntegerField(blank=True, null=True)),
                ('time_in_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_publish', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=80, null=True)),
                ('profile_photo', models.ImageField(default='user-profile.png', upload_to='uploads/player_profile')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('education', models.CharField(blank=True, max_length=20, null=True)),
                ('resume', models.FileField(default=None, upload_to='resumes/')),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True)),
                ('team', models.CharField(blank=True, max_length=30, null=True)),
                ('team_icon', models.ImageField(default=None, upload_to='uploads/team_icon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('time_in', models.CharField(blank=True, max_length=10, null=True)),
                ('time_out', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
